kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem